CREATE SEQUENCE "XXL_JOB_INFO_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_INFO" (
  "ID" NUMBER  NOT NULL,
  "JOB_GROUP" NUMBER  NOT NULL,
  "JOB_DESC" varchar2(255 BYTE)  NOT NULL,
  "ADD_TIME" DATE ,
  "UPDATE_TIME" DATE ,
  "AUTHOR" varchar2(64 BYTE) ,
  "ALARM_EMAIL" varchar2(255 BYTE) ,
  "SCHEDULE_TYPE" varchar2(50 BYTE)  DEFAULT 'NONE' NOT NULL,
  "SCHEDULE_CONF" varchar2(128 BYTE) ,
  "MISFIRE_STRATEGY" varchar2(50 BYTE)  DEFAULT 'DO_NOTHING' NOT NULL,
  "EXECUTOR_ROUTE_STRATEGY" varchar2(50 BYTE) ,
  "EXECUTOR_HANDLER" varchar2(255 BYTE) ,
  "EXECUTOR_PARAM" varchar2(512 BYTE) ,
  "EXECUTOR_BLOCK_STRATEGY" varchar2(50 BYTE) ,
  "EXECUTOR_TIMEOUT" NUMBER  DEFAULT '0' NOT NULL,
  "EXECUTOR_FAIL_RETRY_COUNT" NUMBER  DEFAULT '0' NOT NULL,
  "GLUE_TYPE" varchar2(50 BYTE)  NOT NULL,
  "GLUE_SOURCE" CLOB ,
  "GLUE_REMARK" varchar2(128 BYTE) ,
  "GLUE_UPDATETIME" DATE ,
  "CHILD_JOBID" varchar2(255 BYTE) ,
  "TRIGGER_STATUS" NUMBER  DEFAULT '0' NOT NULL,
  "TRIGGER_LAST_TIME" NUMBER  DEFAULT '0' NOT NULL,
  "TRIGGER_NEXT_TIME" NUMBER  DEFAULT '0' NOT NULL
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "XXL_JOB_INFO"."ID" IS '主键ID';
COMMENT ON COLUMN "XXL_JOB_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_INFO"."JOB_DESC" IS '任务描述';
COMMENT ON COLUMN "XXL_JOB_INFO"."ADD_TIME" IS '添加时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "XXL_JOB_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "XXL_JOB_INFO"."SCHEDULE_TYPE" IS '调度类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."SCHEDULE_CONF" IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."MISFIRE_STRATEGY" IS '调度过期策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_TIMEOUT" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."CHILD_JOBID" IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_STATUS" IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_LAST_TIME" IS '上次调度时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_NEXT_TIME" IS '下次调度时间';

CREATE SEQUENCE "XXL_JOB_LOG_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_LOG" (
  "ID" NUMBER  NOT NULL,
  "JOB_GROUP" NUMBER  NOT NULL,
  "JOB_ID" NUMBER  NOT NULL,
  "EXECUTOR_ADDRESS" varchar2(255 BYTE) ,
  "EXECUTOR_HANDLER" varchar2(255 BYTE) ,
  "EXECUTOR_PARAM" varchar2(512 BYTE) ,
  "EXECUTOR_SHARDING_PARAM" varchar2(20 BYTE) ,
  "EXECUTOR_FAIL_RETRY_COUNT" NUMBER  DEFAULT '0' NOT NULL,
  "TRIGGER_TIME" DATE ,
  "TRIGGER_CODE" NUMBER  NOT NULL,
  "TRIGGER_MSG" CLOB ,
  "HANDLE_TIME" DATE ,
  "HANDLE_CODE" NUMBER  NOT NULL,
  "HANDLE_MSG" CLOB ,
  "ALARM_STATUS" NUMBER  DEFAULT '0' NOT NULL
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "XXL_JOB_LOG"."ID" IS '主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_SHARDING_PARAM" IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_MSG" IS '执行-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."ALARM_STATUS" IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

CREATE SEQUENCE "XXL_JOB_LOG_REPORT_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_LOG_REPORT" (
  "ID" NUMBER  NOT NULL,
  "TRIGGER_DAY" DATE ,
  "RUNNING_COUNT" NUMBER  DEFAULT '0' NOT NULL,
  "SUC_COUNT" NUMBER  DEFAULT '0' NOT NULL,
  "FAIL_COUNT" NUMBER  DEFAULT '0' NOT NULL,
  "UPDATE_TIME" DATE
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."ID" IS '主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."TRIGGER_DAY" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."RUNNING_COUNT" IS '运行中-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."SUC_COUNT" IS '执行成功-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."FAIL_COUNT" IS '执行失败-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."UPDATE_TIME" IS '更新时间';

CREATE SEQUENCE "XXL_JOB_LOGGLUE_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_LOGGLUE" (
  "ID" NUMBER  NOT NULL,
  "JOB_ID" NUMBER  NOT NULL,
  "GLUE_TYPE" varchar2(50 BYTE) ,
  "GLUE_SOURCE" CLOB ,
  "GLUE_REMARK" varchar2(128 BYTE)  NOT NULL,
  "ADD_TIME" DATE ,
  "UPDATE_TIME" DATE
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."ID" IS '主键ID';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';

CREATE SEQUENCE "XXL_JOB_REGISTRY_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_REGISTRY" (
  "ID" NUMBER  NOT NULL,
  "REGISTRY_GROUP" varchar2(50 BYTE)  NOT NULL,
  "REGISTRY_KEY" varchar2(255 BYTE)  NOT NULL,
  "REGISTRY_VALUE" varchar2(255 BYTE)  NOT NULL,
  "UPDATE_TIME" DATE
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

CREATE SEQUENCE "XXL_JOB_GROUP_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_GROUP" (
  "ID" NUMBER  NOT NULL,
  "APP_NAME" varchar2(64 BYTE)  NOT NULL,
  "TITLE" varchar2(30 BYTE)  NOT NULL,
  "ADDRESS_TYPE" NUMBER  DEFAULT '0' NOT NULL,
  "ADDRESS_LIST" CLOB ,
  "UPDATE_TIME" DATE
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "XXL_JOB_GROUP"."ID" IS '主键ID';
COMMENT ON COLUMN "XXL_JOB_GROUP"."APP_NAME" IS '执行器AppName';
COMMENT ON COLUMN "XXL_JOB_GROUP"."TITLE" IS '执行器名称';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';
COMMENT ON COLUMN "XXL_JOB_GROUP"."UPDATE_TIME" IS '更新时间';

CREATE SEQUENCE "XXL_JOB_USER_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_USER" (
  "ID" NUMBER  NOT NULL,
  "USERNAME" varchar2(50 BYTE)  NOT NULL,
  "PASSWORD" varchar2(50 BYTE)  NOT NULL,
  "ROLE" NUMBER  NOT NULL,
  "PERMISSION" varchar2(255 BYTE)  DEFAULT NULL
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "XXL_JOB_USER"."ID" IS '主键ID';
COMMENT ON COLUMN "XXL_JOB_USER"."USERNAME" IS '账号';
COMMENT ON COLUMN "XXL_JOB_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "XXL_JOB_USER"."ROLE" IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN "XXL_JOB_USER"."PERMISSION" IS '权限：执行器ID列表，多个逗号分割';

CREATE SEQUENCE "XXL_JOB_LOCK_SEQ" MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TABLE "XXL_JOB_LOCK" (
  "LOCK_NAME" varchar2(50 BYTE) NOT NULL
)
TABLESPACE "ROOT_DBS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

COMMENT ON COLUMN "XXL_JOB_LOCK"."LOCK_NAME" IS '锁名称';

INSERT INTO "ROOT"."XXL_JOB_GROUP"("ID", "APP_NAME", "TITLE", "ADDRESS_TYPE", "ADDRESS_LIST", "UPDATE_TIME") VALUES (1, 'xxl-job-executor-sample', '示例执行器', 0, NULL, TO_DATE('2018-11-03 22:21:31','SYYYY-MM-DD HH24:MI:SS') );
INSERT INTO "ROOT"."XXL_JOB_INFO"("ID", "JOB_GROUP", "JOB_DESC", "ADD_TIME", "UPDATE_TIME", "AUTHOR", "ALARM_EMAIL", "SCHEDULE_TYPE", "SCHEDULE_CONF", "MISFIRE_STRATEGY", "EXECUTOR_ROUTE_STRATEGY", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_BLOCK_STRATEGY", "EXECUTOR_TIMEOUT", "EXECUTOR_FAIL_RETRY_COUNT", "GLUE_TYPE", "GLUE_SOURCE", "GLUE_REMARK", "GLUE_UPDATETIME", "CHILD_JOBID") VALUES (1, 1, '测试任务1', TO_DATE('2018-11-03 22:21:31','SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-11-03 22:21:31','SYYYY-MM-DD HH24:MI:SS'), 'XXL', '', 'CRON', '0 0 0 * * ? *', 'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', TO_DATE('2018-11-03 22:21:31','SYYYY-MM-DD HH24:MI:SS'), '');
INSERT INTO "ROOT"."XXL_JOB_USER"("ID", "USERNAME", "PASSWORD", "ROLE", "PERMISSION") VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);
INSERT INTO "ROOT"."XXL_JOB_LOCK" ("LOCK_NAME") VALUES ( 'schedule_lock');

commit;

